import Head from 'next/head';
import Swiper from 'react-id-swiper';
import 'swiper/swiper.min.css';
import styles from '../styles/Home.module.css';

export default function Home() {
  const slides = [
    {
      slideNo: 1,
      color: '#011f4b'
    },
    {
      slideNo: 2,
      color: '#03396c'
    },
    {
      slideNo: 3,
      color: '#005b96'
    },
    {
      slideNo: 4,
      color: '#6497b1'
    },
    {
      slideNo: 5,
      color: '#b3cde0'
    },
  ];

  return (
    <div>
      <Head>
        <title>React Id Swiper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Swiper>
        {slides.map(slide => 
          <div
            key={slide.slideNo}
            style={{backgroundColor: slide.color}}
            className={styles.slide}
          >
            Slide # {slide.slideNo}
          </div>
        )}
      </Swiper>
    </div>
  )
}
